name: terraform deploy

on:
  push:
    branches:
      - master

jobs:
  terraform-deploy-job:
    name: Terraform code deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5

      - name: Reworking dev infra deploy
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS__KEY }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform init
          terraform plan
